export enum NotificationType {
  MAP_SHARE_REQUESTED = 100,
  MAP_SHARE_ACCEPTED = 101,
  MAP_SHARE_REJECTED = 102,
  MAP_SESSION_STARTED = 103,
  MAP_SESSION_ENDED = 104,
  MAP_SESSION_EXPIRED = 105,
  MAP_MOMENT_CREATED = 110,
  MAP_MOMENT_EXPIRED = 111,
}
